### ISSUE TITLE
Create definition table?

### ISSUE THREAD

**Issue by lindsayad** [arfc/publications#2]
@katyhuff You mentioned something about adding a mammoth definition table. Can you elaborate more? Do you mean something along the lines of [Cammi's definition table](https://github.com/arfc/publications/files/993464/Cammi_multiphysics_model.pdf)? Or was this taken care of by your nice in-line equation definitions?

**Comment by katyhuff** [comment]
I mean a table of each parameter used as input *in the simulation* (potentially one table for each, neutronics, thermal hydraulics, etc) and the reference for where that data came from.

 
|      |               |            |            |
|-----|-----------|---------------|--------|
|   param   |    val           |    units        |   source         |
| k_th | 3.4 | W/m*K | \cite{robertson} |
| c_p |  | W/m*K | \cite{robertson} |
| G | 2 | # | N/A |
| I | 6 | # | N/A |
| .  |  .  |  .  |   .  |
| .  |  .  |  .  |   .  |
| .  |  .  |  .  |   .  |
| .  |  .  |  .  |   .  |
| .  |  .  |  .  |   .  |

like so
![image](https://cloud.githubusercontent.com/assets/393899/25959041/1a1c8830-3638-11e7-9b6d-5cf448888316.png)

**Comment by lindsayad** [comment]
Oh yea...my memory is so short haha

**Comment by katyhuff** [comment]
no problem! You've probably noticed that I can't retain things that I hear. I have to see them too.

**Comment by lindsayad** [comment]
Closed by #5
