### ISSUE TITLE
Moltres init: improve summarization of state of MSR art / bibliographical research

### ISSUE THREAD

**Issue by gridley** [arfc/publications#38]
Overall, improve support for claim that Moltres can provide unmatched fidelity in coupled neutronics / liquid fuel TH.

These important related articles were not reviewed:

- Manuele Aufiero, Antonio Cammi, Olivier Geoffroy, Mario Losa, Lelio Luzzi, Marco E. Ricotti, Hervé Rouch, Development of an OpenFOAM model for the Molten Salt Fast Reactor transient analysis, Chemical Engineering Science, Volume 111, 2014, Pages 390-401, ISSN 0009-2509, http://dx.doi.org/10.1016/j.ces.2014.03.003.
(http://www.sciencedirect.com/science/article/pii/S0009250914001146)

- Carlo Fiorina, Danny Lathouwers, Manuele Aufiero, Antonio Cammi, Claudia Guerrieri, Jan Leen Kloosterman, Lelio Luzzi, Marco Enrico Ricotti, Modelling and analysis of the MSFR transient behaviour, Annals of Nuclear Energy, Volume 64, 2014, Pages 485-498, ISSN 0306-4549, http://dx.doi.org/10.1016/j.anucene.2013.08.003.
(http://www.sciencedirect.com/science/article/pii/S0306454913004118)

- Matteo Zanetti, Antonio Cammi, Carlo Fiorina, Lelio Luzzi, A Geometric Multiscale modelling approach to the analysis of MSR plant dynamics, Progress in Nuclear Energy, Volume 83, 2015, Pages 82-98, ISSN 0149-1970, http://dx.doi.org/10.1016/j.pnucene.2015.02.014.

- A. Laureau, D. Heuer, E. Merle-Lucotte, P.R. Rubiolo, M. Allibert, M. Aufiero, Transient coupled calculations of the Molten Salt Fast Reactor using the Transient Fission Matrix approach, Nuclear Engineering and Design, Volume 316, 2017, Pages 112-124, ISSN 0029-5493, http://dx.doi.org/10.1016/j.nucengdes.2017.02.022.

- Chinese (probably SINAP) articles should be reviewed too.

In addition, this point also fits into this github issue:

> - The authors write:
"Moltres is devoted to previously unmatched fidelity in coupled neutronics and thermal hydraulics MSR simulation."
This is an overstatement as codes with similar degree of fidelity have been written in the past. This is the case of the tools developed in the frame of the Evol project, as well as e.g. the work from Aufiero on the coupling between OpenFOAM and Serpent (that the authors mention earlier in the introduction). The authors are required to modify this sentence based on a better bibliographical research.

**Comment by katyhuff** [comment]
Closed with #59
