### ISSUE TITLE
Moltres init: discuss issue of open-source nature of Moltres being thwarted by neutronics laws

### ISSUE THREAD

**Issue by gridley** [arfc/publications#39]
Address this:

> Concerning the openness of the code and the possibility to contribute to it, it should be noted that codes solving for neutron transport can be subject to export restrictions (following their potential dual use), and in principle all contributors should get an export control authorization from their own country. The authors are not strictly required to change the manuscript, but they may consider mentioning the fact that the openness of a nuclear code can be somewhat thwarted by national and international laws.

We could possibly find and cite some laws relevant to why neutronics code may typically not be open source. In addition, since the code only models diffusion neutronics, the updated paper could argue that authorities won't bring down the export-control hammer due to its relatively easily-implemented, low order nature.

**Comment by katyhuff** [comment]
see #60

**Comment by katyhuff** [comment]
closed with #60
