### ISSUE TITLE
Moltres init: smaller clarifications

### ISSUE THREAD

**Issue by gridley** [arfc/publications#41]
- Are all equations solved on the same mesh? In this case, is this a strict requirement? Please clarify.

- The heat generation in the graphite is calculated as a fraction of that in the fuel. How exactly is this achieved considering that the two sources are spatially separated?

- It is not clear how the domain is discretized. Is there a radial discretization in graphite and channels? Was the mesh convergence checked? Please discuss.

- The MSRE had Reynolds numbers very close to the laminar-turbulent transition. Did you use a laminar model? In case, did you encounter convergence problems ?
Or did you include turbulence? More generally, is Moltres capable of turbulent simulations?

- The authors are required to use the international system of units (meters, Kelvin, etc).

- The authors should briefly describe what "MSRE design models" are. Otherwise it is very difficult for the readers to assess the accuracy of the model.

- Is the heat generation in the hottest channel the same for the Moltres and the MSRE model?

- The authors claim an unprecedented accuracy of their model? How the results of their model compare with previous results from other authors? The presented results do not seem sufficient to support such claim.

- The differences between the MSRE and the Moltres model are significant and should be discussed in more details. In particular the difference between fast fluxes is suspicious.

**Comment by katyhuff** [comment]
(just fyi @lindsayad I'm a little behind and am still working on this today. Should be done shortly.)

**Comment by lindsayad** [comment]
No problem. Going to see about doing the monolithic vs segregated today or sometime this weekend.

**Comment by katyhuff** [comment]
#63 handles most, but not all, of the issues in this issue.

The following four must be handled before this issue can be closed.

- The heat generation in the graphite is calculated as a fraction of that in the fuel. How exactly is this achieved considering that the two sources are spatially separated?
- It is not clear how the domain is discretized. Is there a radial discretization in graphite and channels? Was the mesh convergence checked? Please discuss.
- Is the heat generation in the hottest channel the same for the Moltres and the MSRE model?
- The differences between the MSRE and the Moltres model are significant and should be discussed in more details. In particular the difference between fast fluxes is suspicious.

**Comment by katyhuff** [comment]
@gridley handled the heat generation question. Three remaining comments must be handled before this issue can be closed:

- It is not clear how the domain is discretized. Is there a radial discretization in graphite and channels? Was the mesh convergence checked? Please discuss.
- Is the heat generation in the hottest channel the same for the Moltres and the MSRE model?
- The differences between the MSRE and the Moltres model are significant and should be discussed in more details. In particular the difference between fast fluxes is suspicious.

**Comment by lindsayad** [comment]
Has anyone recently reviewed the ORNL reports? (I'm wondering maybe @andrewryh ?) I'm wondering whether they give data/calculations about the power generation, specifically in the hottest channel?

**Comment by andrewryh** [comment]
@lindsayad I did not remember measurements of the power generation at all.
But I gonna try to find some calculations right now.

**Comment by andrewryh** [comment]
ORNL-3708 (the report which you use to compare neutron flux distribution):

`When filled, the core, having a nominal volume of 90 ft3, contains
20 ft3 of fuel salt and 70 ft3 of graphite. At 10 Mw, with no fuel absorbed
by the graphite, 1.4 Mw of heat is generated in the fuel outside the nominal core volume, 0.6 Mw is generated in the graphite, and 8.0 Mw
is generated in the fuel within the core, giving an average power density
of 14 kw/liter in the nominal core. **The maximum power density is calculated
to be 31 kw/liter.** `

As I understand there is max power density in the hottest channel.
@lindsayad Or you need axial power density distribution in the hottest channel?

**Comment by lindsayad** [comment]
Closed by #66

**Comment by lindsayad** [comment]
Closed by #66
