### ISSUE TITLE
Moltres init: In-depth scaling tests

### ISSUE THREAD

**Issue by gridley** [arfc/publications#42]
> The proposed scaling test is very limited. Proper scaling tests would require weak and strong scaling tests, an assessment on the impact of the size of problem per core, a separate assessment of intra-node and extra-node scaling, etc. In addition, information should be provided on the employed numerical algorithms and on the parallelization strategy. The authors should either extend significantly the section, or remove it completely.

Maybe other MOOSE results could presented, and then present some Moltres results in the same terms. This would show that the solvers and parallelization provided by MOOSE work well for the physics exhibited by MSRs.

**Comment by andrewryh** [comment]
I can do strong and weak scaling study for moltres on BW, learning it right now in my Parallel Algos class.
If interested, pick your favorite case which is appropriate for the study.

**Comment by lindsayad** [comment]
How big should the problem be?

**Comment by andrewryh** [comment]
It depends on how deep we want to study that. You have mentioned 608 cores in an introduction, but I think 320 cores (10 nodes) quite enough.
So, pick a problem which requires ~2-10 minutes on 320 cores.

For weak scaling we have to fix a number of points per processor, so, I will scale mesh while changing core number, hope I know how to do it in gmsh.

@katyhuff Don't you mind if I'd take this assignment?

**Comment by katyhuff** [comment]
@andrewryh Sounds good to me, but it's up to alex. I think he thought this topic was interesting and self-assigned it .

**Comment by lindsayad** [comment]
You go for it Andrei. I'll look at concocting a problem then and pass it onto you

**Comment by lindsayad** [comment]
@andrewryh I think I would run `moltres/problems/publication_level_cases/3d_steady_state/3d_auto_diff_rho.i` and change `end_time` to something like 1 second. You might have to make it even smaller to get a simulation time in the minute to ten minutes range.

**Comment by andrewryh** [comment]
Gotcha.
I'll change somehow mesh to variate number of grid point per processor also.
Thank, don't forget assign it to me :)

**Comment by katyhuff** [comment]
Closed with  #58
