### ISSUE TITLE
Table 3 cleanup

### ISSUE THREAD

**Issue by katyhuff** [arfc/publications#45]
Table 3 currently looks like this:

![image](https://user-images.githubusercontent.com/393899/31862167-4f224e3c-b6ff-11e7-8726-4c853192e82f.png)

I understand that some entries were positioned across PWR and BWR to indicate that those values apply to both. I like the idea, but unfortunately it's confusing to read. This is complicated by the need to add a caveat to the Lifetime row. Ideally, tables should be set up to avoid lengthy caveats. 

I have a few edits and will assign this fix to myself.

**Comment by katyhuff** [comment]
There are other issues with this table that I am also going to fix.

- the pwr table and the sfr table could be combined... how many batches per core did you assume for SFRs? Just one, probably... I've left some dashes where more information should be added.
- much of this information has come from duderstadt, so I added that book to the bibliography.
- the unit for burnup is usually not plural in tons (it's normalized by tons, so the unit is GWd per ton). So... it should be GWd/ton. More specifically, it usu GWd/MTIHM or GWd/tHM.
- There is no reason to state, in the row labels, that you're referring to PWR Cycle time or PWR Refuelling outage. The reactor type is listed in the column label.
- the number of assemblies per batch is not well described as '1/3 of the core'. I think the intention was probably to have a column "batches per core." If that's the case, the value should be 3.

**Comment by jbae11** [comment]
#47 is merged.
