### ISSUE TITLE
Rearrange sections

### ISSUE THREAD

**Issue by katyhuff** [arfc/publications#48]
In the europe paper  : 

Methodology should include all of the input (historic deployments, predicted european growth, predicted decommissioning, material definitions, reactor details.)

Results should include all of the things that Cyclus and Cycamore produced in the output file and (SFR transition deployment ... which was found through the logic of the Cycamore GrowthRegion.)

Currently, these things are all mixed together. For example:

- All of section 6 should actually be part of section 3.2. 
- Section 3.3 (SFR deployment) should actually be part of results.

I have a pretty solid idea of how I want this to be ordered, so I'm going to give the rearrangement a shot. It will be an ugly PR... brace yourself @jbae11 .

**Comment by jbae11** [comment]
Merged #50
