### ISSUE TITLE
Europe Paper must reference actual cycamore models used 

### ISSUE THREAD

**Issue by katyhuff** [arfc/publications#55]
Imagine you're a stranger trying to reproduce the Europe paper based on the text. Certainly, the input files are available online, but frankly the process is convoluted and it could take quite a while to determine how many of which archetypes were deployed, with what region-instituition-facility models. The paper should include enough information for the reader to know which models we were using (e.g. they should know from reading the paper whether or not we use the growthregion, the deployinst, etc.). It doesn't have to go into enormous detail, but improving the diagram to include region/inst archetype information is appropriate.

**Comment by jbae11** [comment]
Can this and #54 solved by writing several sentences in the Cyclus description section of `DeployInst` and the pre-maturity of `GrowthRegion` ?
