### ISSUE TITLE
Give Moltres paper its own repo

### ISSUE THREAD

**Issue by katyhuff** [arfc/publications#69]
The moltres paper deserves its own repo. (maybe it should have been in its own repo this whole time). In any case, I want to have a logical naming convention for all of the paper repos in this org... so I'm thinking I'll : 

- create a repo called 2017-lindsay-moltres
- move the 2017-lindsay-moltres_init branch (along with all its history) to the master branch of that repo
- add a 'topic' label to that repo called 'paper' so that I can search my repositories for all the papers.
- and maybe try to divorce myself from this publications repo idea entirely.... 

Thoughts (@lindsayad @andrewryh @gridley ) ? Better naming convention ideas? I don't love super long repo names, so maybe we can skip the year? Hopefully we choose this name cleverly enough that I can use this as a model for all future papers in the ARFC group...

**Comment by lindsayad** [comment]
I like the idea. I think Moltres_init (or hypen, whatever you want) would
be enough

**Comment by katyhuff** [comment]
how about moltres-init ? 

(I'm lazy -- lower case letters and hyphens are easier to type than upper case letters and underscores!)

**Comment by katyhuff** [comment]
moltres-intro might even be more clear, since Introduction is the first word of the title.

**Comment by lindsayad** [comment]
I like it. I'm also lazy

**Comment by Daniel-Mietchen** [comment]
+1 for having a dedicated repo per paper.

**Comment by katyhuff** [comment]
done. It's now at [moltres-init](https//github.com/arfc/moltres-init).

**Comment by Daniel-Mietchen** [comment]
Thanks. That link is malformatted; this one works: https://github.com/arfc/moltres-init .

**Comment by katyhuff** [comment]
fixed.
