### ISSUE TITLE
'Growth Trajectory' of EU nations?

### ISSUE THREAD

**Issue by jbae11** [arfc/publications#8]
In order to get the 'growth trajectory' for future extrapolation of EU nations' nuclear program,

what should be the two points that are taken into account?

ie) Bulgria Example
How would one calculate the slope of such a history?
![image](https://cloud.githubusercontent.com/assets/20345275/26233402/bde6e6aa-3c22-11e7-9d6b-5924abaa87c6.png)

**Comment by katyhuff** [comment]
I thought you were going to focus on writing up the 1970-2060 simulation for now...

**Comment by katyhuff** [comment]
What's the status of this issue? Perhaps "won't fix?"

**Comment by jbae11** [comment]
This issue I think, can be closed since we will be predicting only up to 2050.
